### ISSUE TITLE
Version used for pre-sketched viral database

### ISSUE THREAD

**Issue by simeonhebrew** [bluenote-1577/sylph#15]
Hello, thanks for this amazing tool!

Just wanted to confirm which version of the IMG/VR4 database you made the pre-sketched viral database from.
And whether you possess the corresponding metadata file.

Thank you!

**Comment by bluenote-1577** [comment]
Hi @simeonhebrew ,

The data should corresponding to the latest IMG/VR 4.1 _high confidence_  vOTUs. In particular, the sequences were dereplicated to vOTU according to the Metadata files from imgvr.

You can get the Metadata files from https://genome.jgi.doe.gov/portal/IMG_VR/IMG_VR.home.html after creating an account and going to their download page

**Comment by simeonhebrew** [comment]
Okay, thanks!
