### ISSUE TITLE
some question about strain level profile

### ISSUE THREAD

**Issue by zwh82** [bluenote-1577/sylph#20]
Hi, this is indeed a very good tool. I have a question about strain level profile.

`sylph` should be able to add the genomes of multiple strains of a single species to the database, and it can obtain the `Contig_name` of the corresponding strains in the result file `results.tsv`. Does this mean that it can achieve strain level profile, not just species level analysis? If strain level profile can be achieved, what is the accuracy of its abundance estimation?

**Comment by bluenote-1577** [comment]
I would not recommend sylph for strain level profile. Sylph is not designed for strain level profiling.

For very simple cases, sylph may work when multiple strains of a species is in your database. But for realistic metagenomes, sylph's k-mer reassignment strategy is not precise enough for strain-level profiling.

**Comment by zwh82** [comment]
Thanks. I want to know if it is accurate enough to determine whether the strain of metagenomes exists in the database only based on the ANI obtained from the `sylph query`, rather than performing profiling. From this perspective, knowing the existence of certain strains, even without knowing their abundance, is also a significant advancement.

**Comment by bluenote-1577** [comment]
@zwh82 In that case, if you have a database of multiple strains, you can definitely use `sylph query`. It'll give you an estimate of how similar your database strain genomes are compared to the metagenome.

**Comment by zwh82** [comment]
Thanks.
