### ISSUE TITLE
TARA SAGs taxonomic profile

### ISSUE THREAD

**Issue by zackhenny** [bluenote-1577/sylph#24]
Hello, I see that with sylph-utils we have virus, prokaryotic, and Fungi taxonomic information, but no TARA Euk SAG/MAG metadata.tsv to run taxonomic classification on, is there file available somewhere to do this?  I'm also wondering if it is possible to run a profile on some fastqs using both the GTDB and TARA euks info at the same time?  Thank you!!

**Comment by bluenote-1577** [comment]
@zackhenny unfortunately, there is no taxonomic metadata for the TARA Euk's right now. I took a look over their paper, and I think it should be possible from their supplementary tables to get a metadata file. I'll take a look at this later. 

Yes, you can profile with both GTDB and TARA at the same time. Just run

`sylph profile gtdb.syldb tara_euks.syldb -1 read1.fq -2 read2.fq > results.tsv`
and `results.tsv` will use both the databases.

**Comment by bluenote-1577** [comment]
@zackhenny 

I updated `sylph-utils` to v0.4.0. Tara SMAGs now have taxonomy metadata available, so you can generate a nice taxonomic classification.
