### ISSUE TITLE
How to merge the sylph profiles

### ISSUE THREAD

**Issue by LiZhihua1982** [bluenote-1577/sylph#28]
When abtained the MetaPhlAn-like or CAMI-like outputs, how to merge the results of sylph profiles? like https://github.com/biobakery/biobakery/wiki/metaphlan4#15-analyzing-multiple-samples.

**Comment by bluenote-1577** [comment]
See  https://github.com/bluenote-1577/sylph-utils?tab=readme-ov-file#merge_sylph_taxprofpy---merge-multiple-taxonomic-profiles
