### ISSUE TITLE
HELP!!! How to get the file "Refseq_metadataset.tsv.gz"

### ISSUE THREAD

**Issue by Lipapaldl** [bluenote-1577/sylph#38]
![74ea30d6-1514-445e-8e09-6eff03b42b6a](https://github.com/user-attachments/assets/cd35fc8e-d49c-4c80-8967-039f401f08d9)
As shown, **Refseq_metadata.tsv** is missing, can you provide it ？here is my email: raymondnidiffer@gmail.com

**Comment by Lipapaldl** [comment]
When I downloaded the reference database RefSeq CAMI2, I found that the corresponding metadata was missing, making it impossible to reproduce this part of the experiment
当我下载了参考数据库RefSeq CAMI2，发现缺少对应的元数据，导致该部分实验无法复现
```
wget https://openstack.cebitec.uni-bielefeld.de:8080/swift/v1/CAMI_2_DATABASES/RefSeq_genomic_20190108.tar
``` 
![Uploading 8cde07cd-45ed-425a-b00c-87dd361a0012.png…]()

**Comment by Lipapaldl** [comment]
@bluenote-1577

**Comment by bluenote-1577** [comment]
@Lipapaldl we did used taxonkit by shen wei to turn into cami2 format when we did benchmarking. 

See https://bioinf.shenwei.me/taxonkit/ and profile2cami

**Comment by Lipapaldl** [comment]
I noticed the project **profile2cami**, may I ask how to get **the profile of the Refseq** reference gene library（CAMI2）

**Comment by bluenote-1577** [comment]
I am not sure what you mean by refseq gene library. the cami refseq download will include a taxonomy. You will have to convert sylphs output to a TAXID from the downloaded taxonomy. This is from the official cami release
