### ISSUE TITLE
debug and trace option do nothing with prebuilt binaries

### ISSUE THREAD

**Issue by fplaza** [bluenote-1577/sylph#8]
Hi @bluenote-1577,

Maybe it's on purpose, but the debug and trace option do not generate a different output.
Yet, I am interested by some statistics such as the number of deduplicated reads.

**Comment by bluenote-1577** [comment]
Hi @fplaza,

I wonder what's going on here... can you show me the exact steps you do to recreate the problem? I tried and was able to get it working with the prebuilt binary.

**Comment by fplaza** [comment]
My bad.
I was using one hyphen (-debug) instead of two (--debug) so the sketches were written in the "ebug" directory
